project_name: resticprofile
env:
  - RESTIC_VERSION=0.13.1

before:
  hooks:
    - go mod download
    - go generate ./...
    - curl -LO https://github.com/restic/restic/releases/download/v{{ .Env.RESTIC_VERSION }}/restic_{{ .Env.RESTIC_VERSION }}_linux_amd64.bz2
    - bunzip2 restic_{{ .Env.RESTIC_VERSION }}_linux_amd64.bz2
    - mv restic_{{ .Env.RESTIC_VERSION }}_linux_amd64 build/restic-amd64
    - chmod +x build/restic-amd64
    - curl -LO https://github.com/restic/restic/releases/download/v{{ .Env.RESTIC_VERSION }}/restic_{{ .Env.RESTIC_VERSION }}_linux_arm64.bz2
    - bunzip2 restic_{{ .Env.RESTIC_VERSION }}_linux_arm64.bz2
    - mv restic_{{ .Env.RESTIC_VERSION }}_linux_arm64 build/restic-arm64
    - chmod +x build/restic-arm64

builds:
  - id: resticprofile_targz
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

  - id: resticprofile_zip
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
    goarch:
      - "386"
      - amd64

archives:
  - id: targz
    builds:
    - resticprofile_targz
    format: tar.gz

  - id: zip
    builds:
    - resticprofile_zip
    format: zip
    
checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - image_templates:
    - "creativeprojects/resticprofile:latest-amd64"
    - "creativeprojects/resticprofile:{{ .RawVersion }}-amd64"
    ids:
    - resticprofile_targz
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: build/Dockerfile
    extra_files:
    - build/restic-amd64
    build_flag_templates:
    - "--platform=linux/amd64"
    - "--build-arg=ARCH=amd64"
  - image_templates:
    - "creativeprojects/resticprofile:latest-arm64v8"
    - "creativeprojects/resticprofile:{{ .RawVersion }}-arm64v8"
    ids:
    - resticprofile_targz
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: build/Dockerfile
    extra_files:
    - build/restic-arm64
    build_flag_templates:
    - "--platform=linux/arm64/v8"
    - "--build-arg=ARCH=arm64"

docker_manifests:
  - name_template: creativeprojects/resticprofile:{{ .RawVersion }}
    image_templates:
    - creativeprojects/resticprofile:{{ .RawVersion }}-amd64
    - creativeprojects/resticprofile:{{ .RawVersion }}-arm64v8
  - name_template: creativeprojects/resticprofile:latest
    image_templates:
    - creativeprojects/resticprofile:latest-amd64
    - creativeprojects/resticprofile:latest-arm64v8

brews:
  - 
    name: resticprofile
    ids:
      - targz
    goarm: "6"
    tap:
      owner: creativeprojects
      name: "homebrew-tap"
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaser
      email: fred@creativeprojects.tech
    folder: Formula
    homepage: https://github.com/creativeprojects/{{ .ProjectName }}
    description: Configuration profiles for restic backup
    license: "GPL-3.0-only"
    custom_block: |
      head "https://github.com/creativeprojects/{{ .ProjectName }}.git"
    dependencies:
      - name: restic
        type: optional
    install: |
      bin.install "{{ .ProjectName }}"
    test: |
      (testpath/"restic_repo").mkdir
      (testpath/"password.txt").write("key")
      (testpath/"profiles.yaml").write <<~EOS
        default:
          repository: "local:#{testpath}/restic_repo"
          password-file: "password.txt"
          initialize: true
      EOS

      (testpath/"testfile").write("This is a testfile")

      system "#{bin}/resticprofile", "backup", "testfile"
      system "#{bin}/resticprofile", "restore", "latest", "-t", "#{testpath}/restore"
      assert compare_file "testfile", "#{testpath}/restore/testfile"

release:
  draft: true
