language: python

matrix:
  include:
    - name: "Python 3.5 on Linux"
      python: 3.5
    - name: "Python 3.6 on Linux"
      python: 3.6
    - name: "Python 3.7 on Linux"
      python: 3.7
    - name: "Python 3.6 on macOS X"
      os: osx
      language: shell
    - name: "Python 3.7 on Windows"
      os: windows
      language: shell
      before_install: choco install -y python
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - pip3 install -r requirements.txt

script:
  - python3 -m pytest --version || pip3 install pytest
  - PYTHONPATH=./src python3 -m pytest
